import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import security from 'eslint-plugin-security';
import globals from 'globals';

export default [
  {
    ignores: [
      'dist/**',
      'doc/**',
      'coverage/**',
      '.nyc_output/**',
      // generated by `npm run generate:schemas`
      'src/schemas/index.ts'
    ]
  },

  js.configs.recommended,
  security.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.mocha,
        NodeJS: 'readonly'
      }
    },
    rules: {
      'no-empty': ['error', { allowEmptyCatch: true }],
      'prefer-destructuring': ['warn', { object: true, array: false }],
      'no-dupe-class-members': ['warn'],
      'no-useless-constructor': ['warn'],
      'no-unused-vars': ['warn'],
      'constructor-super': ['warn'],
      // carried over from eslint-config-oceanprotocol, which pulled these in
      // via eslint-config-standard; both packages are eslintrc-only and were
      // dropped for eslint 10's flat config
      camelcase: ['warn', { properties: 'never', ignoreGlobals: true }],
      'no-use-before-define': [
        'warn',
        { functions: false, classes: false, variables: false }
      ],
      // https://github.com/nodesecurity/eslint-plugin-security/issues/21
      'security/detect-object-injection': 'off'
    }
  },

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: { jsx: false },
        project: ['./tsconfig.json']
      }
    },
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      // the TS compiler already reports these, and the core rules produce
      // false positives on type-only and overload declarations
      'no-unused-vars': 'off',
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': ['warn']
    }
  },

  prettierRecommended
];
