
export * from './DDO4/Asset'
export * from './DDO4/ConsumerParameter'
export * from './DDO4/Credentials'
export * from './DDO4/DDO'
export * from './DDO4/Event'
export * from './DDO4/Metadata'
export * from './DDO4/Service'

export { Algorithm as AlgorithmV5 } from './DDO5/Algorithm'
export { Asset as AssetV5 } from './DDO5/Asset'
export * from './DDO5/Compute'

export { Credential as CredentialV5 } from './DDO5/Credential'
export * from './DDO5/CredentialSubject'
export { Event as EventV5 } from './DDO5/Event'
export { Metadata as MetadataV5 } from './DDO5/Metadata'
export * from './DDO5/Proof'
export * from './DDO5/Remote'
export { Service as ServiceV5 } from './DDO5/Service'
export * from './DDO5/State'
export * from './DDO5/VerifiableCredential'
